title: Book Connect
description: "Your Personal Reading Companion - Track, Connect, and Enhance Your Reading Journey"
owner_name: Jacob Zierolf
github_username: jacobcancode
github_repo: "book-connect"
baseurl: "/book-connect"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/reading_tools.md
  - navigation/reading_tracker.md
  - navigation/book_club.md
  - navigation/recommendations.md
  - navigation/profile.md
